# Site settings
email: 
baseurl: "jug-nn.ru"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: JUG NN
description: The site of the Java group of Nizhnij Novgorod, Russia
url: ""
twitter_username: 
default_img: 

# Profile settings
name: 
profile_img: testOlen.png
profile: 
social:
  github: 

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
